//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSanGo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string email { get; set; }
        public string payment_method { get; set; }
        public string address { get; set; }
        public Nullable<int> total_product { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> time_order { get; set; }
        public string payment_status { get; set; }
    
        public virtual user user { get; set; }
    }
}
